image: docker

services:
  - name: docker:dind

variables:
  # Platforms to support builds for
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"

# Order in which jobs are executed
stages:
  - build-dev
  - trigger-integration-testing

# Login to the docker registry to access your private registry
before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

# Build a docker image with the dev tag each time a new commit
# is pushed to the main branch or a merge request is updated
release-dev-docker:
  tags:
    - docker-build # Gitlab runner to use (must support docker build)
  stage: build-dev
  script:
    # Setup multi-platform build context
    - docker run --privileged --rm multiarch/qemu-user-static --reset -p yes
    - docker context create multiplatformcontext
    - docker buildx create --name multiplatformbuilder --use multiplatformcontext
    # Build the image to multiple platforms
    - docker buildx build --platform "$PLATFORMS" -t "$CI_REGISTRY_IMAGE:dev" --push --provenance=false . # PATH TO Docker file, currently root (.)
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

